export default {
  WEB_PAGE: 'WEB_PAGE',
  STATIC_VIDEO: 'STATIC_VIDEO',
  GUIDE_INTERACTION: 'GUIDE_INTERACTION',
  FREEPLAY: 'FREEPLAY',
  LIVESTREAM: 'LIVESTREAM',
  VIDEO_CHOICE: 'VIDEO_CHOICE',
  KICK: 'KICK'
}