name: main

on:
  push:
    branches: main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Show Service builder
        uses: docker/setup-buildx-action@v1
        id: show_builder
      - name: Set up Load Test Maestro builder
        uses: docker/setup-buildx-action@v1
        id: maestro_builder
      - name: Set up Load Test Drone builder
        uses: docker/setup-buildx-action@v1
        id: drone_builder
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Show Service
        id: show_docker_build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.show_builder.outputs.name }}
          context: ./show-service
          file: ./show-service/Dockerfile
          push: true
          tags: scatteredplayers/show:x86
      - name: Build and push Load Test Maestro
        id: maestro_docker_build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.maestro_builder.outputs.name }}
          context: ./load-testing/maestro
          file: ./load-testing/maestro/Dockerfile
          push: true
          tags: scatteredplayers/maestro:x86
      - name: Build and push Load Test Drone
        id: drone_docker_build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.drone_builder.outputs.name }}
          context: ./load-testing/maestro
          file: ./load-testing/maestro/Dockerfile
          push: true
          tags: scatteredplayers/drone:x86