name: main

on:
  push:
    branches: main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push show service
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./show-service
          file: ./show-service/Dockerfile
          push: true
          tags: scatteredplayers/show:x86
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}