name: main

on:
  push:
    branches: main

jobs:
  services:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Show Service builder
        uses: docker/setup-buildx-action@v1
        id: show_builder
      - name: Set up Load Test Maestro builder
        uses: docker/setup-buildx-action@v1
        id: maestro_builder
      - name: Set up Load Test Drone builder
        uses: docker/setup-buildx-action@v1
        id: drone_builder
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Show Service
        id: show_docker_build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.show_builder.outputs.name }}
          context: ./show-service
          file: ./show-service/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: scatteredplayers/show:multiplatform
  #     - name: Build and push Load Test Maestro
  #       id: maestro_docker_build
  #       uses: docker/build-push-action@v2
  #       with:
  #         builder: ${{ steps.maestro_builder.outputs.name }}
  #         context: ./load-testing/maestro
  #         file: ./load-testing/maestro/Dockerfile
  #         platforms: linux/amd64,linux/arm64
  #         push: true
  #         tags: scatteredplayers/maestro:multiplatform
  #     - name: Build and push Load Test Drone
  #       id: drone_docker_build
  #       uses: docker/build-push-action@v2
  #       with:
  #         builder: ${{ steps.drone_builder.outputs.name }}
  #         context: ./load-testing/drone
  #         file: ./load-testing/drone/Dockerfile
  #         platforms: linux/amd64
  #         push: true
  #         tags: scatteredplayers/drone:multiplatform